apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webapp-review
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: cindyhu-gd
        repo: argocd-course-webapp
        labels:
        - preview
      requeueAfterSeconds: 60
  template:
    metadata:
      name: 'myapp-{{branch}}-{{number}}'
      namespace: argocd
    spec:
      source:
        repoURL: 'https://github.com/cindyhu-gd/argocd-course-webapp'
        targetRevision: '{{head_sha}}'
        path: helm/webapp
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true